apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: echo-server-pod-kill
spec:
  schedule: "@every 10s"
  type: "PodChaos"
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: "pod-kill"
    mode: "one"
    selector:
      labelSelectors:
        "app": "echo-server"
